// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: [
    'README',
    {
      type: 'category',
      label: 'Onshape model',
      collapsed: false,
      items: [
        'onshape-model-overview',
        'onshape-migration',
        'onshape-mcp-cookbook',
      ],
    },
    {
      type: 'category',
      label: 'Build',
      collapsed: false,
      items: [
        'build-assembly-guide',
        'competition-2026-06-06',
        'competition-2026-06-06-bom',
        'competition-2026-06-06-build-log',
      ],
    },
    {
      type: 'category',
      label: 'Firmware',
      collapsed: false,
      items: [
        'firmware-setup',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      items: [
        'roadmap',
        {
          type: 'category',
          label: 'Decisions (ADRs)',
          link: {type: 'generated-index', slug: '/decisions'},
          items: [{type: 'autogenerated', dirName: 'decisions'}],
        },
      ],
    },
  ],
};

export default sidebars;
